# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorizationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.resize(403, 340)
        AuthWindow.setStyleSheet("background-color: rgb(176, 224, 230)")
        self.centralwidget = QtWidgets.QWidget(AuthWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 60, 281, 211))
        self.groupBox.setStyleSheet("background-color: white;\n"
"font: 10pt Times New Roman")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 91, 16))
        self.label_2.setStyleSheet("font: 10pt Times New Roman")
        self.label_2.setObjectName("label_2")
        self.userPassword = QtWidgets.QLineEdit(self.groupBox)
        self.userPassword.setGeometry(QtCore.QRect(150, 100, 113, 22))
        self.userPassword.setObjectName("userPassword")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 70, 111, 16))
        self.label.setStyleSheet("font: 10pt Times New Roman")
        self.label.setObjectName("label")
        self.userName = QtWidgets.QLineEdit(self.groupBox)
        self.userName.setGeometry(QtCore.QRect(150, 70, 113, 22))
        self.userName.setObjectName("userNam")
        self.buttonAuth = QtWidgets.QPushButton(self.groupBox)
        self.buttonAuth.setGeometry(QtCore.QRect(20, 150, 81, 21))
        self.buttonAuth.setStyleSheet("background-color: rgb(154, 205, 50);\n"
"font: 10pt Times New Roman")
        self.buttonAuth.setObjectName("buttonExit")
        AuthWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AuthWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "Авторизация"))
        self.label_2.setText(_translate("AuthWindow", "Пароль"))
        self.label.setText(_translate("AuthWindow", "Пользователь"))
        self.buttonAuth.setText(_translate("AuthWindow", "Вход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AuthWindow = QtWidgets.QMainWindow()
    ui = Ui_AuthWindow()
    ui.setupUi(AuthWindow)
    AuthWindow.show()
    sys.exit(app.exec_())
