# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/authorizationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authorization(object):
    def setupUi(self, authorization):
        authorization.setObjectName("authorization")
        authorization.setWindowModality(QtCore.Qt.ApplicationModal)
        authorization.resize(410, 300)
        authorization.setMinimumSize(QtCore.QSize(410, 300))
        authorization.setMaximumSize(QtCore.QSize(410, 300))
        authorization.setAutoFillBackground(False)
        authorization.setStyleSheet("background-color:rgb(211, 211, 211)")
        self.user_name = QtWidgets.QLineEdit(authorization)
        self.user_name.setGeometry(QtCore.QRect(120, 130, 161, 22))
        self.user_name.setStyleSheet("background-color: white")
        self.user_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.user_name.setObjectName("user_name")
        self.label_3 = QtWidgets.QLabel(authorization)
        self.label_3.setGeometry(QtCore.QRect(90, 50, 221, 51))
        self.label_3.setStyleSheet("font: 16pt corbel;\n"
"color: black")
        self.label_3.setObjectName("label_3")
        self.user_password = QtWidgets.QLineEdit(authorization)
        self.user_password.setGeometry(QtCore.QRect(120, 170, 161, 22))
        self.user_password.setStyleSheet("background-color: white")
        self.user_password.setText("")
        self.user_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.user_password.setObjectName("user_password")
        self.button_entrance = QtWidgets.QPushButton(authorization)
        self.button_entrance.setGeometry(QtCore.QRect(270, 240, 93, 28))
        self.button_entrance.setStyleSheet("")
        self.button_entrance.setObjectName("button_entrance")
        self.label = QtWidgets.QLabel(authorization)
        self.label.setGeometry(QtCore.QRect(80, 120, 31, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui/img/user.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(authorization)
        self.label_2.setGeometry(QtCore.QRect(80, 170, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ui/img/key.png"))
        self.label_2.setObjectName("label_2")
        self.tabBar = QtWidgets.QGroupBox(authorization)
        self.tabBar.setGeometry(QtCore.QRect(0, 0, 410, 40))
        self.tabBar.setStyleSheet("background-color: black; font: 10pt")
        self.tabBar.setTitle("")
        self.tabBar.setObjectName("tabBar")
        self.button_info = QtWidgets.QPushButton(self.tabBar)
        self.button_info.setGeometry(QtCore.QRect(330, 5, 31, 31))
        self.button_info.setStyleSheet("color: white")
        self.button_info.setText("")
        self.button_info.setObjectName("button_info")
        self.button_close = QtWidgets.QPushButton(self.tabBar)
        self.button_close.setGeometry(QtCore.QRect(370, 5, 31, 31))
        self.button_close.setStyleSheet("color: white")
        self.button_close.setText("")
        self.button_close.setObjectName("button_close")

        self.retranslateUi(authorization)
        QtCore.QMetaObject.connectSlotsByName(authorization)

    def retranslateUi(self, authorization):
        _translate = QtCore.QCoreApplication.translate
        authorization.setWindowTitle(_translate("authorization", "Авторизация"))
        self.label_3.setText(_translate("authorization", "Добро пожаловать"))
        self.button_entrance.setText(_translate("authorization", "Вход"))
